# Shows messages if errors occur, possibly other useful messages in the future
verbose: true

# Shows messages with debug information
debug: false

# The naem of the rank defined below which all players start with, set to "" to disable
defaultRank: player

# Permissions are generally stated as "pluginname.permissionname", you can assign permission nodes to different ranks here.
# Use the scperms_giverank command to give a player a rank (or scperms_givetemprank for testing, the rank is then removed on server restart).
# If you have set conflicting permissions a higher rank will always override a lower one as players can have several ranks at the same time.
# The 'vanillarank' node gives players ranks designated in the vanilla config so you don't have to enter the players in both systems
permissions:
    admin:
        vanillarank: admin
        scpermissions.reload: true
        scpermissions.verbose: true
        scpermissions.debug: true
        scpermissions.giverank: true
        scpermissions.removerank: true
        scpermissions.giverank: true
        scpermissions.removerank: true

    moderator:
        vanillarank: moderator
        scpermissions.giverank: true
        scpermissions.removerank: true

    donator:
        vanillarank: donator
        customloadouts.donatorloadouts: true

    restricted:
        vanillarank: restricted
        customloadouts.playerloadouts: false

    player:
        customloadouts.playerloadouts: true